apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ls4-jan212026-3-app
  namespace: openshift-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/ls4-jan212026-3/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/ls4-jan212026-3-gitops.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: hello2
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

