apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: ls4-jan212026-3
  janus-idp.io/tekton: ls4-jan212026-3
  backstage.io/kubernetes-id: ls4-jan212026-3
  backstage.io/kubernetes-namespace: hello2
  app.kubernetes.io/part-of: ls4-jan212026-3
resources:
  - application-dev.yaml
