# Service for Streamlit UI Application
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ls4-jan212026-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ls4-jan212026-3
  name: ls4-jan212026-3
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
      name: http
  selector:
    app.kubernetes.io/instance: ls4-jan212026-3

